tombs.register_stones('caverealms:glow_amethyst', 'glow_amethyst', 'Glow Amethyst', 'caverealms_glow_amethyst', 5)
tombs.register_stones('caverealms:glow_crystal', 'glow_crystal', 'Glow Crystal', 'caverealms_glow_crystal', 5)
tombs.register_stones('caverealms:glow_ruby', 'glow_ruby', 'Glow Ruby', 'caverealms_glow_ruby', 5)
tombs.register_stones('caverealms:glow_emerald', 'glow_emerald', 'Glow Emerald', 'caverealms_glow_emerald', 5)
tombs.register_stones('caverealms:glow_mese', 'glow_mese', 'Glow Mese', 'caverealms_glow_mese', 5)
tombs.register_stones('caverealms:salt_crystal', 'salt_crystal', 'Salt Crystal', 'caverealms_salt_crystal')
tombs.register_stones('caverealms:hot_cobble', 'hot_cobble', 'Hot Cobble', 'caverealms_hot_cobble', 6)
tombs.register_stones('caverealms:glow_obsidian', 'glow_obsidian', 'Glow Obsidian', 'caverealms_glow_obsidian', 5)
tombs.register_stones('caverealms:glow_obsidian_2', 'glow_obsidian_2', 'Glow Obsidian', 'caverealms_glow_obsidian', 5)
tombs.register_stones('caverealms:mushroom_cap', 'mushroom_cap', 'Mushroom Cap', 'caverealms_mushroom_cap')
tombs.register_stones('caverealms:mushroom_stem', 'mushroom_stem', 'Mushroom Stem', 'caverealms_mushroom_stem')
