tombs.register_stones('darkage:adobe', 'adobe', 'Adobe', 'darkage_adobe')
tombs.register_stones('darkage:basalt', 'basalt', 'Basalt', 'darkage_basalt')
tombs.register_stones('darkage:basalt_rubble', 'basalt_rubble', 'Basalt Rubble', 'darkage_basalt_rubble')
tombs.register_stones('darkage:chalk', 'chalk', 'Chalk', 'darkage_chalk')
tombs.register_stones('darkage:gneiss', 'gneiss', 'Gneiss', 'darkage_gneiss')
tombs.register_stones('darkage:gneiss_rubble', 'gneiss_rubble', 'Gneiss Rubble', 'darkage_gneiss_rubble')
tombs.register_stones('darkage:marble', 'marble', 'Marble', 'darkage_marble')
tombs.register_stones('darkage:ors', 'ors', 'Old Red Sandstone', 'darkage_ors')
tombs.register_stones('darkage:ors', 'ors_rubble', 'Old Red Sandstone Rubble', 'darkage_ors_rubble')
tombs.register_stones('darkage:rhyolitic_tuff', 'rhyolitic_tuff', 'Rhyolitic Tuff', 'darkage_rhyolitic_tuff')
tombs.register_stones('darkage:rhyolitic_tuff_rubble', 'rhyolitic_tuff_rubble', 'Rhyolitic Tuff Rubble', 'darkage_rhyolitic_tuff_rubble')
tombs.register_stones('darkage:schist', 'schist', 'Schist', 'darkage_schist')
tombs.register_stones('darkage:serpentine', 'serpentine', 'Serpentine', 'darkage_serpentine')
tombs.register_stones('darkage:shale', 'shale', 'Shale', 'darkage_shale')
tombs.register_stones('darkage:slate', 'slate', 'Slate', 'darkage_slate')
tombs.register_stones('darkage:slate_rubble', 'slate_rubble', 'Slate Rubble', 'darkage_slate_rubble')
tombs.register_stones('darkage:slate_tile', 'slate_tile', 'Slate Tile', 'darkage_slate_tile')
tombs.register_stones('darkage:tuff', 'tuff', 'Tuff', 'darkage_tuff')
tombs.register_stones('darkage:tuff_rubble', 'tuff_rubble', 'Tuff Rubble', 'darkage_tuff_rubble')
