tombs.register_stones('ethereal:acacia_wood', 'acacia', 'Acacia', 'default_acacia_wood')
tombs.register_stones('ethereal:banana_wood', 'banana', 'Banana', 'banana_wood')
tombs.register_stones('ethereal:crystal_moss', 'crystal_moss', 'Crystal Moss', 'ethereal_grass_crystal_top')
tombs.register_stones('ethereal:fiery_moss', 'fiery_moss', 'Fiery Moss', 'ethereal_grass_fiery_top')
tombs.register_stones('ethereal:frost_wood', 'frost_wood', 'Frost Wood', 'frost_wood')
tombs.register_stones('ethereal:glostone', 'glostone', 'Glostone', 'glostone', 10)
tombs.register_stones('ethereal:grey_moss', 'grey_moss', 'Grey Moss', 'ethereal_grass_gray_top')
tombs.register_stones('ethereal:green_moss', 'green_moss', 'Green Moss', 'default_grass')
tombs.register_stones('ethereal:mushroom', 'mushroomcap', 'Mushroom Cap', 'mushroom_block')
tombs.register_stones('ethereal:mushroom_pore', 'mushroompore', 'Mushroom Pore', 'mushroom_pore')
tombs.register_stones('ethereal:palm_wood', 'palm_wood', 'Palm', 'moretrees_palm_wood')
tombs.register_stones('ethereal:redwood_wood', 'redwood_wood', 'Redwood', 'redwood_wood')
tombs.register_stones('ethereal:willow_wood', 'willow_wood', 'Willow', 'willow_wood')
tombs.register_stones('ethereal:yellow_wood', 'yellow_wood', 'Healing Wood', 'yellow_wood')
