tombs.register_stones('geominer:diorite', 'diorite', 'Diorite', 'geominer_diorite')
tombs.register_stones('geominer:gneiss', 'geogneiss', 'Gneiss', 'geominer_gneiss_top')
tombs.register_stones('geominer:diorite', 'diorite', 'Diorite', 'geominer_diorite')
tombs.register_stones('geominer:granite', 'granite', 'Granite', 'geominer_granite')
tombs.register_stones('geominer:hell_stone', 'hell_stone', 'Hell Stone', 'geominer_hell_stone')
tombs.register_stones('geominer:limestone', 'limestone', 'Limestone', 'geominer_limestone')
tombs.register_stones('geominer:marble', 'geomarble', 'Marble', 'geominer_marble')
tombs.register_stones('geominer:peridotite', 'peridotite', 'Peridotite', 'geominer_peridotite_top')
tombs.register_stones('geominer:scoria', 'scoria', 'Scoria', 'geominer_scoria')
tombs.register_stones('geominer:slate', 'geoslate', 'Slate', 'geominer_slate')
