tombs.register_stones('moretrees:apple_tree_planks', 'apple', 'Apple', 'moretrees_apple_tree_wood')
tombs.register_stones('moretrees:beech_planks', 'beech', 'Beech', 'moretrees_beech_wood')
tombs.register_stones('moretrees:birch_planks', 'birch', 'Birch', 'moretrees_birch_wood')
tombs.register_stones('moretrees:cedar_planks', 'cedar', 'Cedar', 'moretrees_beech_wood')
tombs.register_stones('moretrees:date_palm_planks', 'date_palm', 'Date Palm', 'moretrees_date_palm_wood')
tombs.register_stones('moretrees:fir_planks', 'fir', 'Fir', 'moretrees_fir_wood')
tombs.register_stones('moretrees:oak_planks', 'oak', 'Oak', 'moretrees_oak_wood')
tombs.register_stones('moretrees:palm_planks', 'palm', 'Palm', 'moretrees_palm_wood')
tombs.register_stones('moretrees:poplar_planks', 'poplar', 'Poplar', 'moretrees_poplar_wood')
tombs.register_stones('moretrees:rubber_tree_planks', 'rubber_tree', 'Rubber Tree', 'moretrees_rubber_tree_wood')
tombs.register_stones('moretrees:sequoia_planks', 'sequoia', 'Sequoia', 'moretrees_sequoia_wood')
tombs.register_stones('moretrees:spruce_planks', 'spruce', 'Spruce', 'moretrees_spruce_wood')
tombs.register_stones('moretrees:willow_planks', 'willow', 'Willow', 'moretrees_willow_wood')
